#
# Copyright 2021 Jens A. Koch.
# SPDX-License-Identifier: MIT
# This file is part of jakoch/jupyter-devbox.
# Modified by @birkenbube
#

name: Release

on:
  # You can manually run this workflow.
  workflow_dispatch:
  # This workflow runs on pushing a semantic versionized tag (e.g. v1.0.0).
  # This workflow does not run when pushing to the main branch.
  push:
    #branches:
    #  - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  # This workflow runs on schedule: every Sunday at 2 am.
  schedule:
    - cron: "0 2 * * 0"

env:
  GHCR_IMAGE: ghcr.io/${{ github.repository }}

jobs:

# ---------------------------------------------------------------------------------------

  build:

# ---------------------------------------------------------------------------------------

    name: "Build Container"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.0 # https://github.com/jlumbroso/free-disk-space
        with:
          tool-cache: true
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v4 # https://github.com/actions/checkout

      - name: Login to Github Container Registry (GHCR)
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3 # https://github.com/docker/login-action
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Metadata
        id: metadata
        uses: docker/metadata-action@v5 # https://github.com/docker/metadata-action/
        with:
          images: |
            ${{ env.GHCR_IMAGE }}
          flavor: |
            latest=auto
          tags: |
            type=schedule,pattern={{ date 'YYYYMMDD' }}
            type=semver,pattern={{ version }}
            type=semver,pattern={{ major }}.{{ minor }}
            type=raw,value={{ date 'YYYYMMDD' }}-sha-{{ sha }},enabled=${{ github.event_name == 'push' }}
            type=raw,value=latest

      - name: Create info.json
        run: |
          jq -n --arg version "${{ github.ref_name }}" --arg commit "${{ github.sha }}" --arg date "$(date -u +%F)" '{ version: $version, commit: $commit, date: $date }' > info.json


      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          imageName: ghcr.io/${{ github.repository }}
          push: always
          # imageTag: ${{ steps.metadata.outputs.labels }}
